runtime: python38 # Replace with your desired Python runtime version

entrypoint: gunicorn -b :$PORT main:app # Replace 'main' with the name of your Python script if necessary

instance_class: F2 # Adjust this based on your application's resource requirements

env_variables:
  FLASK_ENV: production # Set Flask environment to production
